/* 生成全新 EN_PRACTICE（21 天 × 10 句），覆盖外贸/差旅/商务场景，与上周不重复 */
const fs = require('fs');

const DAYS = [
  { // 0 机场值机与登机
    lines: [
      {role:`A`, en:`Good morning, may I see your passport and ticket?`, zh:`早上好，请出示您的护照和机票好吗？`},
      {role:`B`, en:`Sure, here you are.`, zh:`好的，给您。`},
      {role:`A`, en:`Will you be checking any bags?`, zh:`您要托运行李吗？`},
      {role:`B`, en:`Just one suitcase.`, zh:`只托运一个行李箱。`},
      {role:`A`, en:`Window or aisle seat?`, zh:`靠窗还是靠走道？`},
      {role:`B`, en:`Aisle, please.`, zh:`请给我靠走道的。`},
      {role:`A`, en:`Your gate is C7, boarding at 10:40.`, zh:`您的登机口是 C7，10:40 登机。`},
      {role:`B`, en:`How do I get to the gate?`, zh:`怎么去登机口？`},
      {role:`A`, en:`Take the shuttle train to Terminal 2.`, zh:`坐捷运列车到 T2 航站楼。`},
      {role:`B`, en:`Thank you, have a good day.`, zh:`谢谢，祝您一天愉快。`},
    ],
    speak: [`May I see your passport and ticket?`, `Window or aisle seat?`, `How do I get to the gate?`],
    words: [
      {w:`passport`, ph:`/ˈpæspɔːrt/`, zh:`护照`},
      {w:`ticket`, ph:`/ˈtɪkɪt/`, zh:`机票`},
      {w:`boarding pass`, ph:`/ˈbɔːrdɪŋ pæs/`, zh:`登机牌`},
      {w:`gate`, ph:`/ɡeɪt/`, zh:`登机口`},
      {w:`luggage`, ph:`/ˈlʌɡɪdʒ/`, zh:`行李`},
      {w:`suitcase`, ph:`/ˈsuːtkeɪs/`, zh:`行李箱`},
      {w:`aisle seat`, ph:`/aɪl siːt/`, zh:`靠走道座位`},
      {w:`window seat`, ph:`/ˈwɪndoʊ siːt/`, zh:`靠窗座位`},
      {w:`terminal`, ph:`/ˈtɜːrmɪnl/`, zh:`航站楼`},
      {w:`shuttle`, ph:`/ˈʃʌtl/`, zh:`穿梭/捷运`},
      {w:`depart`, ph:`/dɪˈpɑːrt/`, zh:`出发`},
      {w:`boarding`, ph:`/ˈbɔːrdɪŋ/`, zh:`登机`},
    ]
  },
  { // 1 酒店入住与退房
    lines: [
      {role:`A`, en:`Good evening, do you have a reservation?`, zh:`晚上好，您有预订吗？`},
      {role:`B`, en:`Yes, under the name Li.`, zh:`有，用 Li 这个名字预订的。`},
      {role:`A`, en:`Your room is 1210. Here is your key card.`, zh:`您的房间是 1210，这是您的房卡。`},
      {role:`B`, en:`What time is breakfast served?`, zh:`早餐几点供应？`},
      {role:`A`, en:`6:30 to 10, on the third floor.`, zh:`6:30 到 10 点，在三楼。`},
      {role:`B`, en:`Could I get a wake-up call at 7?`, zh:`能帮我设早上 7 点的叫早电话吗？`},
      {role:`A`, en:`Certainly, 7 a.m. sharp.`, zh:`当然，7 点整。`},
      {role:`B`, en:`Is there a socket for my laptop?`, zh:`房间有笔记本电脑的插座吗？`},
      {role:`A`, en:`Yes, by the desk, and USB ports too.`, zh:`有，在书桌旁，还有 USB 接口。`},
      {role:`B`, en:`Great, I will check out on Friday.`, zh:`好的，我周五退房。`},
    ],
    speak: [`Do you have a reservation?`, `What time is breakfast served?`, `I will check out on Friday.`],
    words: [
      {w:`reservation`, ph:`/ˌrezərˈveɪʃn/`, zh:`预订`},
      {w:`check in`, ph:`/tʃek ɪn/`, zh:`入住`},
      {w:`check out`, ph:`/tʃek aʊt/`, zh:`退房`},
      {w:`key card`, ph:`/kiː kɑːrd/`, zh:`房卡`},
      {w:`breakfast`, ph:`/ˈbrekfəst/`, zh:`早餐`},
      {w:`wake-up call`, ph:`/ˈweɪk ʌp kɔːl/`, zh:`叫早电话`},
      {w:`lobby`, ph:`/ˈlɑːbi/`, zh:`大堂`},
      {w:`socket`, ph:`/ˈsɑːkɪt/`, zh:`插座`},
      {w:`reception`, ph:`/rɪˈsepʃn/`, zh:`前台`},
      {w:`floor`, ph:`/flɔːr/`, zh:`楼层`},
      {w:`deposit`, ph:`/dɪˈpɑːzɪt/`, zh:`押金`},
      {w:`luggage storage`, ph:`/ˈlʌɡɪdʒ ˈstɔːrɪdʒ/`, zh:`行李寄存`},
    ]
  },
  { // 2 餐厅点餐与账单
    lines: [
      {role:`W`, en:`Are you ready to order?`, zh:`您准备好点餐了吗？`},
      {role:`G`, en:`What's today's special?`, zh:`今天的特色菜是什么？`},
      {role:`W`, en:`The spicy beef with cumin is popular.`, zh:`孜然辣牛肉很受欢迎。`},
      {role:`G`, en:`I'll have that, and a bowl of rice.`, zh:`我要那份，再加一碗米饭。`},
      {role:`W`, en:`How spicy would you like it?`, zh:`您要多辣？`},
      {role:`G`, en:`Medium spicy, please.`, zh:`中辣，谢谢。`},
      {role:`W`, en:`Anything to drink?`, zh:`喝点什么？`},
      {role:`G`, en:`Just sparkling water, no ice.`, zh:`气泡水就好，不要冰。`},
      {role:`W`, en:`Sure. Anything else?`, zh:`好的，还要别的吗？`},
      {role:`G`, en:`No, could we have the bill later?`, zh:`不用，账单稍后给我们好吗？`},
    ],
    speak: [`What's today's special?`, `Medium spicy, please.`, `Could we have the bill later?`],
    words: [
      {w:`menu`, ph:`/ˈmenjuː/`, zh:`菜单`},
      {w:`order`, ph:`/ˈɔːrdər/`, zh:`点餐`},
      {w:`special`, ph:`/ˈspeʃl/`, zh:`特色菜`},
      {w:`spicy`, ph:`/ˈspaɪsi/`, zh:`辣的`},
      {w:`medium`, ph:`/ˈmiːdiəm/`, zh:`中等的`},
      {w:`rice`, ph:`/raɪs/`, zh:`米饭`},
      {w:`drink`, ph:`/drɪŋk/`, zh:`饮料`},
      {w:`sparkling water`, ph:`/ˈspɑːrklɪŋ ˈwɔːtər/`, zh:`气泡水`},
      {w:`bill`, ph:`/bɪl/`, zh:`账单`},
      {w:`tip`, ph:`/tɪp/`, zh:`小费`},
      {w:`fork`, ph:`/fɔːrk/`, zh:`叉子`},
      {w:`knife`, ph:`/naɪf/`, zh:`刀`},
    ]
  },
  { // 3 展会摊位接待客户
    lines: [
      {role:`S`, en:`Welcome to our booth. What brings you here?`, zh:`欢迎来到我们的展位，您主要想看什么？`},
      {role:`B`, en:`I'm looking for OEM suppliers for smart lamps.`, zh:`我在找智能灯的 OEM 供应商。`},
      {role:`S`, en:`Great, this is our latest model. May I have your card?`, zh:`太好了，这是我们最新款，能留张名片吗？`},
      {role:`B`, en:`Sure, here you go.`, zh:`好的，给您。`},
      {role:`S`, en:`Are you buying for your own brand or reselling?`, zh:`您是自牌采购还是转售？`},
      {role:`B`, en:`We have our own brand in Europe.`, zh:`我们在欧洲有自己的品牌。`},
      {role:`S`, en:`Nice. What's your monthly volume?`, zh:`好，您月用量大概多少？`},
      {role:`B`, en:`Around 20,000 units to start.`, zh:`起步大约两万件。`},
      {role:`S`, en:`Let me note that. I'll email you the catalog.`, zh:`我记一下，稍后把目录发给您。`},
      {role:`B`, en:`Perfect, talk soon.`, zh:`太好了，回头聊。`},
    ],
    speak: [`What brings you here?`, `Are you buying for your own brand or reselling?`, `I'll email you the catalog.`],
    words: [
      {w:`booth`, ph:`/buːð/`, zh:`展位`},
      {w:`supplier`, ph:`/səˈplaɪər/`, zh:`供应商`},
      {w:`OEM`, ph:`/ˌoʊ iː ˈem/`, zh:`代工生产`},
      {w:`model`, ph:`/ˈmɑːdl/`, zh:`型号`},
      {w:`business card`, ph:`/ˈbɪznəs kɑːrd/`, zh:`名片`},
      {w:`brand`, ph:`/brænd/`, zh:`品牌`},
      {w:`resell`, ph:`/ˌriːˈsel/`, zh:`转售`},
      {w:`volume`, ph:`/ˈvɑːljuːm/`, zh:`销量/量`},
      {w:`catalog`, ph:`/ˈkætəlɔːɡ/`, zh:`目录`},
      {w:`sample`, ph:`/ˈsæmpl/`, zh:`样品`},
      {w:`inquiry`, ph:`/ɪnˈkwaɪəri/`, zh:`询盘`},
      {w:`lead`, ph:`/liːd/`, zh:`潜在客户`},
    ]
  },
  { // 4 工厂参观与产线介绍
    lines: [
      {role:`G`, en:`Thanks for showing us around.`, zh:`谢谢带我们参观。`},
      {role:`F`, en:`My pleasure. This is our assembly line.`, zh:`我的荣幸，这是我们的装配线。`},
      {role:`G`, en:`How many units per day?`, zh:`每天产能多少？`},
      {role:`F`, en:`About 5,000 units on two shifts.`, zh:`两班倒大约 5000 件。`},
      {role:`G`, en:`What's your defect rate?`, zh:`不良率多少？`},
      {role:`F`, en:`Under 0.5% thanks to full inspection.`, zh:`全检之下低于 0.5%。`},
      {role:`G`, en:`Do you have the ISO certificates?`, zh:`你们有 ISO 认证吗？`},
      {role:`F`, en:`Yes, ISO 9001 and BSCI.`, zh:`有，ISO 9001 和 BSCI。`},
      {role:`G`, en:`Can we see the warehouse?`, zh:`能看看仓库吗？`},
      {role:`F`, en:`Sure, this way.`, zh:`当然，这边请。`},
    ],
    speak: [`How many units per day?`, `What's your defect rate?`, `Do you have the ISO certificates?`],
    words: [
      {w:`factory`, ph:`/ˈfæktri/`, zh:`工厂`},
      {w:`assembly line`, ph:`/əˈsembli laɪn/`, zh:`装配线`},
      {w:`shift`, ph:`/ʃɪft/`, zh:`班次`},
      {w:`defect rate`, ph:`/dɪˈfekt reɪt/`, zh:`不良率`},
      {w:`inspection`, ph:`/ɪnˈspekʃn/`, zh:`检验`},
      {w:`certificate`, ph:`/sərˈtɪfɪkət/`, zh:`证书`},
      {w:`warehouse`, ph:`/ˈwerhaʊs/`, zh:`仓库`},
      {w:`capacity`, ph:`/kəˈpæsəti/`, zh:`产能`},
      {w:`production`, ph:`/prəˈdʌkʃn/`, zh:`生产`},
      {w:`quality`, ph:`/ˈkwɑːləti/`, zh:`质量`},
      {w:`machinery`, ph:`/məˈʃiːnəri/`, zh:`机械`},
      {w:`safety`, ph:`/ˈseɪfti/`, zh:`安全`},
    ]
  },
  { // 5 样品寄送与物流跟进
    lines: [
      {role:`S`, en:`Your samples were sent yesterday by DHL.`, zh:`您的样品昨天已通过 DHL 寄出。`},
      {role:`B`, en:`Great, what's the tracking number?`, zh:`太好了，运单号是多少？`},
      {role:`S`, en:`It's 8829 1123 4456. ETA three days.`, zh:`8829 1123 4456，预计三天到。`},
      {role:`B`, en:`Please use our Shenzhen warehouse as the address.`, zh:`请寄到我们在深圳的仓库。`},
      {role:`S`, en:`Noted. Do you need a commercial invoice?`, zh:`记下了，需要商业发票吗？`},
      {role:`B`, en:`Yes, for customs clearance.`, zh:`要，用于清关。`},
      {role:`S`, en:`I'll attach it to the email.`, zh:`我会附在邮件里。`},
      {role:`B`, en:`Also, mark the carton "Fragile".`, zh:`另外，箱子标上"易碎"。`},
      {role:`S`, en:`Will do.`, zh:`会的。`},
      {role:`B`, en:`Thanks, keep me posted.`, zh:`谢谢，有进展告诉我。`},
    ],
    speak: [`What's the tracking number?`, `Please use our Shenzhen warehouse.`, `Keep me posted.`],
    words: [
      {w:`sample`, ph:`/ˈsæmpl/`, zh:`样品`},
      {w:`ship`, ph:`/ʃɪp/`, zh:`发货`},
      {w:`tracking number`, ph:`/ˈtrækɪŋ ˈnʌmbər/`, zh:`运单号`},
      {w:`courier`, ph:`/ˈkʊriər/`, zh:`快递`},
      {w:`ETA`, ph:`/ˌiː tiː ˈeɪ/`, zh:`预计到达`},
      {w:`warehouse`, ph:`/ˈwerhaʊs/`, zh:`仓库`},
      {w:`commercial invoice`, ph:`/kəˈmɜːrʃl ˈɪnvɔɪs/`, zh:`商业发票`},
      {w:`customs`, ph:`/ˈkʌstəmz/`, zh:`海关`},
      {w:`carton`, ph:`/ˈkɑːrtn/`, zh:`纸箱`},
      {w:`fragile`, ph:`/ˈfrædʒaɪl/`, zh:`易碎`},
      {w:`clearance`, ph:`/ˈklɪrəns/`, zh:`清关`},
      {w:`dispatch`, ph:`/dɪˈspætʃ/`, zh:`发出`},
    ]
  },
  { // 6 价格谈判与报价
    lines: [
      {role:`B`, en:`Your quote is a bit high for our market.`, zh:`你们的报价对我们市场偏高了。`},
      {role:`S`, en:`It reflects the latest material costs.`, zh:`这反映了最新的材料成本。`},
      {role:`B`, en:`If we order 50k, can you do better?`, zh:`如果我们订五万件，能给更好的价吗？`},
      {role:`S`, en:`For that volume, I can offer 5% off.`, zh:`这个量我可以让 5%。`},
      {role:`B`, en:`How about 8% and free tooling?`, zh:`8% 加免开模费如何？`},
      {role:`S`, en:`Let me check with my manager... 6% is my best.`, zh:`我请示下经理……最多 6%。`},
      {role:`B`, en:`Deal at 6%, with FOB Shenzhen.`, zh:`6% 成交，深圳 FOB。`},
      {role:`S`, en:`Agreed. I'll send the revised PI.`, zh:`同意，我发修订后的形式发票。`},
      {role:`B`, en:`Good. Payment by T/T 30% deposit.`, zh:`好，付款用 T/T 30% 定金。`},
      {role:`S`, en:`Perfect, thank you.`, zh:`太好了，谢谢。`},
    ],
    speak: [`Can you do better?`, `How about 8% and free tooling?`, `Deal at 6%, with FOB Shenzhen.`],
    words: [
      {w:`quote`, ph:`/kwoʊt/`, zh:`报价`},
      {w:`negotiation`, ph:`/nɪˌɡoʊʃiˈeɪʃn/`, zh:`谈判`},
      {w:`volume`, ph:`/ˈvɑːljuːm/`, zh:`数量`},
      {w:`discount`, ph:`/ˈdɪskaʊnt/`, zh:`折扣`},
      {w:`tooling`, ph:`/ˈtuːlɪŋ/`, zh:`开模`},
      {w:`FOB`, ph:`/ˌef oʊ ˈbiː/`, zh:`离岸价`},
      {w:`EXW`, ph:`/ˌiː eks ˈdʌbljuː/`, zh:`工厂交货`},
      {w:`deposit`, ph:`/dɪˈpɑːzɪt/`, zh:`定金`},
      {w:`Proforma Invoice`, ph:`/proʊˈfɔːrmə ˈɪnvɔɪs/`, zh:`形式发票`},
      {w:`manager`, ph:`/ˈmænɪdʒər/`, zh:`经理`},
      {w:`cost`, ph:`/kɔːst/`, zh:`成本`},
      {w:`margin`, ph:`/ˈmɑːrdʒɪn/`, zh:`利润`},
    ]
  },
  { // 7 邮件沟通与会议预约
    lines: [
      {role:`A`, en:`I'd like to schedule a call with your team.`, zh:`我想和贵团队安排个通话。`},
      {role:`B`, en:`Sure. What time works for you?`, zh:`好，您什么时间方便？`},
      {role:`A`, en:`Thursday 3 p.m. your time, 30 minutes.`, zh:`你们周四下午 3 点，30 分钟。`},
      {role:`B`, en:`Let me confirm with the team... yes, that works.`, zh:`我和团队确认下……可以。`},
      {role:`A`, en:`Great, I'll send a calendar invite.`, zh:`好，我会发日历邀约。`},
      {role:`B`, en:`Please include the agenda.`, zh:`请附上议程。`},
      {role:`A`, en:`Of course: pricing, lead time, and QA.`, zh:`当然：价格、交期和质量。`},
      {role:`B`, en:`Sounds good. See you then.`, zh:`听起来不错，到时见。`},
      {role:`A`, en:`One more thing, mute your mic when not speaking.`, zh:`还有，不说话时请静音。`},
      {role:`B`, en:`Noted, thanks.`, zh:`记下了，谢谢。`},
    ],
    speak: [`What time works for you?`, `I'll send a calendar invite.`, `Please include the agenda.`],
    words: [
      {w:`schedule`, ph:`/ˈskedʒuːl/`, zh:`安排`},
      {w:`calendar`, ph:`/ˈkælɪndər/`, zh:`日历`},
      {w:`invite`, ph:`/ɪnˈvaɪt/`, zh:`邀约`},
      {w:`agenda`, ph:`/əˈdʒendə/`, zh:`议程`},
      {w:`confirm`, ph:`/kənˈfɜːrm/`, zh:`确认`},
      {w:`time zone`, ph:`/taɪm zoʊn/`, zh:`时区`},
      {w:`minute`, ph:`/ˈmɪnɪt/`, zh:`分钟`},
      {w:`meeting`, ph:`/ˈmiːtɪŋ/`, zh:`会议`},
      {w:`team`, ph:`/tiːm/`, zh:`团队`},
      {w:`reply`, ph:`/rɪˈplaɪ/`, zh:`回复`},
      {w:`attach`, ph:`/əˈtætʃ/`, zh:`附上`},
      {w:`reminder`, ph:`/rɪˈmaɪndər/`, zh:`提醒`},
    ]
  },
  { // 8 视频会议与远程沟通
    lines: [
      {role:`A`, en:`Can everyone see my screen?`, zh:`大家能看到我的屏幕吗？`},
      {role:`B`, en:`Yes, but your audio cuts out.`, zh:`能看到，但您声音断断续续。`},
      {role:`A`, en:`Let me switch to the phone line.`, zh:`我切换到电话线路吧。`},
      {role:`B`, en:`Better now?`, zh:`现在好点了吗？`},
      {role:`A`, en:`Much clearer, thanks.`, zh:`清楚多了，谢谢。`},
      {role:`B`, en:`Let's share the slides on page 5.`, zh:`我们看第 5 页的幻灯片。`},
      {role:`A`, en:`Here is the Q3 forecast.`, zh:`这是第三季度预测。`},
      {role:`B`, en:`The numbers look strong.`, zh:`数据看起来不错。`},
      {role:`A`, en:`Any questions before we wrap up?`, zh:`结束前有疑问吗？`},
      {role:`B`, en:`No, let's circle back next week.`, zh:`没有，我们下周再跟进。`},
    ],
    speak: [`Can everyone see my screen?`, `Let me switch to the phone line.`, `Any questions before we wrap up?`],
    words: [
      {w:`screen`, ph:`/skriːn/`, zh:`屏幕`},
      {w:`share`, ph:`/ʃer/`, zh:`共享`},
      {w:`audio`, ph:`/ˈɔːdioʊ/`, zh:`音频`},
      {w:`video`, ph:`/ˈvɪdioʊ/`, zh:`视频`},
      {w:`mute`, ph:`/mjuːt/`, zh:`静音`},
      {w:`slide`, ph:`/slaɪd/`, zh:`幻灯片`},
      {w:`forecast`, ph:`/ˈfɔːrkæst/`, zh:`预测`},
      {w:`quarter`, ph:`/ˈkwɔːrtər/`, zh:`季度`},
      {w:`connection`, ph:`/kəˈnekʃn/`, zh:`连接`},
      {w:`conference`, ph:`/ˈkɑːnfərəns/`, zh:`会议`},
      {w:`replay`, ph:`/ˌriːˈpleɪ/`, zh:`回放`},
      {w:`network`, ph:`/ˈnetwɜːrk/`, zh:`网络`},
    ]
  },
  { // 9 付款方式与信用证
    lines: [
      {role:`B`, en:`We prefer payment by letter of credit.`, zh:`我们倾向用信用证付款。`},
      {role:`S`, en:`L/C at sight is fine, but slower.`, zh:`即期信用证可以，但较慢。`},
      {role:`B`, en:`How long for the bank to confirm?`, zh:`银行确认要多久？`},
      {role:`S`, en:`Usually 3 to 5 working days.`, zh:`通常 3 到 5 个工作日。`},
      {role:`B`, en:`Can you accept 30% T/T, 70% before shipment?`, zh:`能接受 30% 电汇、70% 发货前付吗？`},
      {role:`S`, en:`That works if you're an established buyer.`, zh:`如果您是老客户就可以。`},
      {role:`B`, en:`We've ordered three times before.`, zh:`我们之前订过三次了。`},
      {role:`S`, en:`Then 30/70 T/T is agreed.`, zh:`那同意 30/70 电汇。`},
      {role:`B`, en:`I'll arrange the deposit today.`, zh:`我今天安排定金。`},
      {role:`S`, en:`Great, I'll start production.`, zh:`太好了，我就开工。`},
    ],
    speak: [`We prefer payment by letter of credit.`, `Can you accept 30% T/T?`, `I'll arrange the deposit today.`],
    words: [
      {w:`payment`, ph:`/ˈpeɪmənt/`, zh:`付款`},
      {w:`letter of credit`, ph:`/ˈletər əv ˈkredɪt/`, zh:`信用证`},
      {w:`T/T`, ph:`/ˌtiː ˈtiː/`, zh:`电汇`},
      {w:`deposit`, ph:`/dɪˈpɑːzɪt/`, zh:`定金`},
      {w:`shipment`, ph:`/ˈʃɪpmənt/`, zh:`发货`},
      {w:`bank`, ph:`/bæŋk/`, zh:`银行`},
      {w:`confirm`, ph:`/kənˈfɜːrm/`, zh:`确认`},
      {w:`working day`, ph:`/ˈwɜːrkɪŋ deɪ/`, zh:`工作日`},
      {w:`sight`, ph:`/saɪt/`, zh:`即期`},
      {w:`established`, ph:`/ɪˈstæblɪʃt/`, zh:`老牌的`},
      {w:`wire`, ph:`/waɪər/`, zh:`电汇`},
      {w:`invoice`, ph:`/ˈɪnvɔɪs/`, zh:`发票`},
    ]
  },
  { // 10 质量问题与客诉处理
    lines: [
      {role:`B`, en:`We found rust on 12% of the batch.`, zh:`我们发现这批货 12% 有锈。`},
      {role:`S`, en:`I'm sorry to hear that. Photos, please?`, zh:`很抱歉听到，方便发照片吗？`},
      {role:`B`, en:`Attached. It's clearly a packaging issue.`, zh:`已附上，明显是包装问题。`},
      {role:`S`, en:`Let me investigate with the plant.`, zh:`我和工厂排查一下。`},
      {role:`B`, en:`We need a refund or replacement.`, zh:`我们需要退款或补货。`},
      {role:`S`, en:`We'll send replacement parts next week.`, zh:`我们下周补发零件。`},
      {role:`B`, en:`And improve the anti-rust coating?`, zh:`防锈涂层也要改进吧？`},
      {role:`S`, en:`Yes, we're updating the process.`, zh:`是的，我们在更新工艺。`},
      {role:`B`, en:`Please keep us updated.`, zh:`请随时告知进展。`},
      {role:`S`, en:`Absolutely, I'll report Friday.`, zh:`一定，我周五汇报。`},
    ],
    speak: [`We found rust on 12% of the batch.`, `We need a refund or replacement.`, `Please keep us updated.`],
    words: [
      {w:`quality`, ph:`/ˈkwɑːləti/`, zh:`质量`},
      {w:`defect`, ph:`/dɪˈfekt/`, zh:`缺陷`},
      {w:`rust`, ph:`/rʌst/`, zh:`锈`},
      {w:`complaint`, ph:`/kəmˈpleɪnt/`, zh:`投诉`},
      {w:`photo`, ph:`/ˈfoʊtoʊ/`, zh:`照片`},
      {w:`refund`, ph:`/ˈriːfʌnd/`, zh:`退款`},
      {w:`replacement`, ph:`/rɪˈpleɪsmənt/`, zh:`替换/补货`},
      {w:`batch`, ph:`/bætʃ/`, zh:`批次`},
      {w:`coating`, ph:`/ˈkoʊtɪŋ/`, zh:`涂层`},
      {w:`investigate`, ph:`/ɪnˈvestɪɡeɪt/`, zh:`排查`},
      {w:`process`, ph:`/ˈprɑːses/`, zh:`工艺`},
      {w:`report`, ph:`/rɪˈpɔːrt/`, zh:`汇报`},
    ]
  },
  { // 11 海关申报与清关
    lines: [
      {role:`B`, en:`Do we need any special license for this item?`, zh:`这个产品需要特殊许可证吗？`},
      {role:`C`, en:`Only if it's regulated. Let me check the HS code.`, zh:`看是否受管制，我查下 HS 编码。`},
      {role:`B`, en:`The HS code is 8517.62.`, zh:`HS 编码是 8517.62。`},
      {role:`C`, en:`That's free, no license needed.`, zh:`那个是免证的，不需要许可。`},
      {role:`B`, en:`What documents for clearance?`, zh:`清关要哪些单据？`},
      {role:`C`, en:`Invoice, packing list, and waybill.`, zh:`发票、装箱单和运单。`},
      {role:`B`, en:`Do you handle customs brokerage?`, zh:`你们做报关代理吗？`},
      {role:`C`, en:`Yes, we clear at Shenzhen port.`, zh:`做，我们在深圳港报关。`},
      {role:`B`, en:`Good, send me the quote.`, zh:`好，把报价发我。`},
      {role:`C`, en:`Will do today.`, zh:`今天发。`},
    ],
    speak: [`Do we need any special license?`, `What documents for clearance?`, `Do you handle customs brokerage?`],
    words: [
      {w:`customs`, ph:`/ˈkʌstəmz/`, zh:`海关`},
      {w:`clearance`, ph:`/ˈklɪrəns/`, zh:`清关`},
      {w:`license`, ph:`/ˈlaɪsns/`, zh:`许可证`},
      {w:`HS code`, ph:`/ˌeɪtʃ ˈes koʊd/`, zh:`HS 编码`},
      {w:`invoice`, ph:`/ˈɪnvɔɪs/`, zh:`发票`},
      {w:`packing list`, ph:`/ˈpækɪŋ lɪst/`, zh:`装箱单`},
      {w:`waybill`, ph:`/ˈweɪbɪl/`, zh:`运单`},
      {w:`broker`, ph:`/ˈbroʊkər/`, zh:`报关行`},
      {w:`declare`, ph:`/dɪˈkler/`, zh:`申报`},
      {w:`port`, ph:`/pɔːrt/`, zh:`港口`},
      {w:`duty`, ph:`/ˈduːti/`, zh:`关税`},
      {w:`tariff`, ph:`/ˈtærɪf/`, zh:`关税税则`},
    ]
  },
  { // 12 出租车/租车与市内交通
    lines: [
      {role:`G`, en:`To the convention center, please.`, zh:`请到会展中心。`},
      {role:`D`, en:`Which entrance, sir?`, zh:`先生，哪个入口？`},
      {role:`G`, en:`The north gate, near Hall 3.`, zh:`北门，3 号馆附近。`},
      {role:`D`, en:`Sure, about 20 minutes.`, zh:`好的，大约 20 分钟。`},
      {role:`G`, en:`Could you turn on the meter?`, zh:`能打表吗？`},
      {role:`D`, en:`It's already on.`, zh:`已经打了。`},
      {role:`G`, en:`Please drop me at the lobby.`, zh:`请在大堂让我下。`},
      {role:`D`, en:`Here we are. 48 yuan.`, zh:`到了，48 元。`},
      {role:`G`, en:`I'll pay by scan.`, zh:`我扫码付。`},
      {role:`D`, en:`Thank you, have a good show.`, zh:`谢谢，祝您展会顺利。`},
    ],
    speak: [`To the convention center, please.`, `Could you turn on the meter?`, `I'll pay by scan.`],
    words: [
      {w:`taxi`, ph:`/ˈtæksi/`, zh:`出租车`},
      {w:`meter`, ph:`/ˈmiːtər/`, zh:`计价器`},
      {w:`fare`, ph:`/fer/`, zh:`车费`},
      {w:`drop`, ph:`/drɑːp/`, zh:`让下（车）`},
      {w:`lobby`, ph:`/ˈlɑːbi/`, zh:`大堂`},
      {w:`entrance`, ph:`/ˈentrəns/`, zh:`入口`},
      {w:`convention`, ph:`/kənˈvenʃn/`, zh:`会展`},
      {w:`scan`, ph:`/skæn/`, zh:`扫码`},
      {w:`change`, ph:`/tʃeɪndʒ/`, zh:`零钱`},
      {w:`receipt`, ph:`/rɪˈsiːt/`, zh:`收据`},
      {w:`route`, ph:`/ruːt/`, zh:`路线`},
      {w:`destination`, ph:`/ˌdestɪˈneɪʃn/`, zh:`目的地`},
    ]
  },
  { // 13 商务宴请与点菜礼仪
    lines: [
      {role:`H`, en:`Welcome, please sit here next to me.`, zh:`欢迎，请坐我旁边。`},
      {role:`G`, en:`Thank you. This restaurant looks great.`, zh:`谢谢，这家餐厅看起来很棒。`},
      {role:`H`, en:`Try the local specialty, it's not too spicy.`, zh:`尝尝当地特色菜，不太辣。`},
      {role:`G`, en:`I'll follow your lead.`, zh:`我听您安排。`},
      {role:`H`, en:`Let me propose a toast to our partnership.`, zh:`我提议为我们的合作干杯。`},
      {role:`G`, en:`Cheers, to a long cooperation.`, zh:`干杯，为长久合作。`},
      {role:`H`, en:`Help yourself to more dishes.`, zh:`请随意多吃点菜。`},
      {role:`G`, en:`Everything is delicious.`, zh:`每道菜都很美味。`},
      {role:`H`, en:`Next time you host in your city.`, zh:`下次在您城市由您做东。`},
      {role:`G`, en:`Absolutely, I'll arrange it.`, zh:`一定，我来安排。`},
    ],
    speak: [`Please sit here next to me.`, `Let me propose a toast to our partnership.`, `Next time you host in your city.`],
    words: [
      {w:`dinner`, ph:`/ˈdɪnər/`, zh:`晚宴`},
      {w:`host`, ph:`/hoʊst/`, zh:`做东`},
      {w:`guest`, ph:`/ɡest/`, zh:`客人`},
      {w:`toast`, ph:`/toʊst/`, zh:`干杯`},
      {w:`partnership`, ph:`/ˈpɑːrtnərʃɪp/`, zh:`合作`},
      {w:`specialty`, ph:`/ˈspeʃəlti/`, zh:`特色菜`},
      {w:`dish`, ph:`/dɪʃ/`, zh:`菜`},
      {w:`cooperate`, ph:`/koʊˈɑːpəreɪt/`, zh:`合作`},
      {w:`etiquette`, ph:`/ˈetɪket/`, zh:`礼仪`},
      {w:`seat`, ph:`/siːt/`, zh:`座位`},
      {w:`cheers`, ph:`/tʃɪrz/`, zh:`干杯`},
      {w:`treat`, ph:`/triːt/`, zh:`请客`},
    ]
  },
  { // 14 询盘与回复
    lines: [
      {role:`B`, en:`We saw your products online. Send a catalog?`, zh:`我们在网上看到你们产品，能发目录吗？`},
      {role:`S`, en:`Sure, may I know your company and market?`, zh:`可以，能了解一下贵司和市场吗？`},
      {role:`B`, en:`We're a distributor in the Middle East.`, zh:`我们是中东的经销商。`},
      {role:`S`, en:`Great. Do you need CE or RoHS?`, zh:`好，你们需要 CE 还是 RoHS？`},
      {role:`B`, en:`Both, plus Arabic labeling.`, zh:`都要，还要阿拉伯语标签。`},
      {role:`S`, en:`Noted. MOQ is 500 sets.`, zh:`记下了，起订量 500 套。`},
      {role:`B`, en:`Can we start with a trial order?`, zh:`能先小批试单吗？`},
      {role:`S`, en:`Yes, 200 sets for the first order.`, zh:`可以，首单 200 套。`},
      {role:`B`, en:`Good. Send the quote by Friday.`, zh:`好，周五前发报价。`},
      {role:`S`, en:`Will do.`, zh:`会的。`},
    ],
    speak: [`Send a catalog?`, `Do you need CE or RoHS?`, `Can we start with a trial order?`],
    words: [
      {w:`inquiry`, ph:`/ɪnˈkwaɪəri/`, zh:`询盘`},
      {w:`catalog`, ph:`/ˈkætəlɔːɡ/`, zh:`目录`},
      {w:`distributor`, ph:`/dɪˈstrɪbjətər/`, zh:`经销商`},
      {w:`market`, ph:`/ˈmɑːrkɪt/`, zh:`市场`},
      {w:`certificate`, ph:`/sərˈtɪfɪkət/`, zh:`证书`},
      {w:`labeling`, ph:`/ˈleɪblɪŋ/`, zh:`贴标`},
      {w:`MOQ`, ph:`/ˌem oʊ ˈkjuː/`, zh:`最小起订量`},
      {w:`trial order`, ph:`/ˈtraɪəl ˈɔːrdər/`, zh:`试单`},
      {w:`quote`, ph:`/kwoʊt/`, zh:`报价`},
      {w:`reply`, ph:`/rɪˈplaɪ/`, zh:`回复`},
      {w:`Middle East`, ph:`/ˈmɪdl iːst/`, zh:`中东`},
      {w:`Arabic`, ph:`/ˈærəbɪk/`, zh:`阿拉伯语`},
    ]
  },
  { // 15 包装与标签要求
    lines: [
      {role:`B`, en:`We need export cartons, not white boxes.`, zh:`我们要出口纸箱，不要白盒。`},
      {role:`S`, en:`Noted, standard brown carton, 12 per box.`, zh:`记下了，标准棕色纸箱，每箱 12 个。`},
      {role:`B`, en:`And a master carton of 6 inner boxes.`, zh:`外箱装 6 个内箱。`},
      {role:`S`, en:`Clear. Any label specs?`, zh:`明白，标签有要求吗？`},
      {role:`B`, en:`Yes, barcode, country of origin, and warnings.`, zh:`有，条码、原产国和警示语。`},
      {role:`S`, en:`Origin is "Made in China".`, zh:`原产国写"中国制造"。`},
      {role:`B`, en:`Also add our logo on the inner box.`, zh:`内箱也要加我们的 logo。`},
      {role:`S`, en:`Sure, we'll send a proof first.`, zh:`好，我们先发确认稿。`},
      {role:`B`, en:`Good, approve before mass run.`, zh:`好，量产前确认。`},
      {role:`S`, en:`Agreed.`, zh:`同意。`},
    ],
    speak: [`We need export cartons.`, `Any label specs?`, `Approve before mass run.`],
    words: [
      {w:`packaging`, ph:`/ˈpækɪdʒɪŋ/`, zh:`包装`},
      {w:`carton`, ph:`/ˈkɑːrtn/`, zh:`纸箱`},
      {w:`inner box`, ph:`/ˈɪnər bɑːks/`, zh:`内箱`},
      {w:`master carton`, ph:`/ˈmæstər ˈkɑːrtn/`, zh:`外箱`},
      {w:`label`, ph:`/ˈleɪbl/`, zh:`标签`},
      {w:`barcode`, ph:`/ˈbɑːrkoʊd/`, zh:`条码`},
      {w:`origin`, ph:`/ˈɔːrɪdʒɪn/`, zh:`原产国`},
      {w:`logo`, ph:`/ˈloʊɡoʊ/`, zh:`商标`},
      {w:`warning`, ph:`/ˈwɔːrnɪŋ/`, zh:`警示`},
      {w:`proof`, ph:`/pruːf/`, zh:`确认稿`},
      {w:`mass production`, ph:`/mæs prəˈdʌkʃn/`, zh:`量产`},
      {w:`spec`, ph:`/spek/`, zh:`规格`},
    ]
  },
  { // 16 交货期与排产沟通
    lines: [
      {role:`B`, en:`What's the lead time for 10k units?`, zh:`一万件的货期多久？`},
      {role:`S`, en:`Normally 25 days after deposit.`, zh:`通常收到定金后 25 天。`},
      {role:`B`, en:`Can you rush it to 18 days?`, zh:`能加急到 18 天吗？`},
      {role:`S`, en:`If we add a night shift, yes.`, zh:`如果加夜班可以。`},
      {role:`B`, en:`Extra cost for the rush?`, zh:`加急有额外费用吗？`},
      {role:`S`, en:`8% surcharge for the night shift.`, zh:`夜班加收 8%。`},
      {role:`B`, en:`Acceptable. Start after the deposit.`, zh:`可以接受，定金到账后开工。`},
      {role:`S`, en:`We'll book the line for week 3.`, zh:`我们排第三周的生产线。`},
      {role:`B`, en:`Keep me posted on progress.`, zh:`进度随时告诉我。`},
      {role:`S`, en:`Weekly updates, promised.`, zh:`每周更新，保证。`},
    ],
    speak: [`What's the lead time for 10k units?`, `Can you rush it to 18 days?`, `Keep me posted on progress.`],
    words: [
      {w:`lead time`, ph:`/liːd taɪm/`, zh:`交货期`},
      {w:`deposit`, ph:`/dɪˈpɑːzɪt/`, zh:`定金`},
      {w:`rush`, ph:`/rʌʃ/`, zh:`加急`},
      {w:`night shift`, ph:`/naɪt ʃɪft/`, zh:`夜班`},
      {w:`surcharge`, ph:`/ˈsɜːrtʃɑːrdʒ/`, zh:`附加费`},
      {w:`schedule`, ph:`/ˈskedʒuːl/`, zh:`排程`},
      {w:`production line`, ph:`/prəˈdʌkʃn laɪn/`, zh:`生产线`},
      {w:`week`, ph:`/wiːk/`, zh:`周`},
      {w:`progress`, ph:`/ˈprɑːɡres/`, zh:`进度`},
      {w:`update`, ph:`/ˈʌpdeɪt/`, zh:`更新`},
      {w:`capacity`, ph:`/kəˈpæsəti/`, zh:`产能`},
      {w:`deadline`, ph:`/ˈdedlaɪn/`, zh:`截止日`},
    ]
  },
  { // 17 索赔与退换货
    lines: [
      {role:`B`, en:`The goods arrived with 30 units broken.`, zh:`货到了，30 件破损。`},
      {role:`S`, en:`So sorry. Do you have the inspection report?`, zh:`很抱歉，有检验报告吗？`},
      {role:`B`, en:`Yes, enclosed with photos.`, zh:`有，附了照片。`},
      {role:`S`, en:`We'll deduct from the next order.`, zh:`我们从下一单扣除。`},
      {role:`B`, en:`Or send replacements this month.`, zh:`或者这个月补发。`},
      {role:`S`, en:`Replacement is faster. I'll arrange it.`, zh:`补货更快，我来安排。`},
      {role:`B`, en:`Also, file a claim with the carrier.`, zh:`另外向承运商提索赔。`},
      {role:`S`, en:`Already done, tracking the case.`, zh:`已经提了，在跟进案件。`},
      {role:`B`, en:`Good. Keep the credit note ready.`, zh:`好，准备好贷记单。`},
      {role:`S`, en:`Will do.`, zh:`会的。`},
    ],
    speak: [`The goods arrived with 30 units broken.`, `Or send replacements this month.`, `File a claim with the carrier.`],
    words: [
      {w:`claim`, ph:`/kleɪm/`, zh:`索赔`},
      {w:`broken`, ph:`/ˈbroʊkən/`, zh:`破损的`},
      {w:`inspection`, ph:`/ɪnˈspekʃn/`, zh:`检验`},
      {w:`report`, ph:`/rɪˈpɔːrt/`, zh:`报告`},
      {w:`deduct`, ph:`/dɪˈdʌkt/`, zh:`扣除`},
      {w:`replacement`, ph:`/rɪˈpleɪsmənt/`, zh:`替换`},
      {w:`carrier`, ph:`/ˈkæriər/`, zh:`承运商`},
      {w:`credit note`, ph:`/ˈkredɪt noʊt/`, zh:`贷记单`},
      {w:`return`, ph:`/rɪˈtɜːrn/`, zh:`退货`},
      {w:`damage`, ph:`/ˈdæmɪdʒ/`, zh:`损坏`},
      {w:`compensate`, ph:`/ˈkɑːmpenseɪt/`, zh:`赔偿`},
      {w:`enclose`, ph:`/ɪnˈkloʊz/`, zh:`附上`},
    ]
  },
  { // 18 代理/分销合作洽谈
    lines: [
      {role:`B`, en:`We'd like to be your agent in Vietnam.`, zh:`我们想做你们在越南的代理。`},
      {role:`S`, en:`Great. What's your coverage?`, zh:`好，你们覆盖哪些区域？`},
      {role:`B`, en:`North and central Vietnam, 20 staff.`, zh:`越南北部和中部，20 名员工。`},
      {role:`S`, en:`Do you have a showroom?`, zh:`你们有展厅吗？`},
      {role:`B`, en:`Yes, in Hanoi, 200 sqm.`, zh:`有，在河内，200 平米。`},
      {role:`S`, en:`We can grant exclusivity for one year.`, zh:`我们可以给一年独家权。`},
      {role:`B`, en:`With a minimum annual target?`, zh:`有最低年任务量吗？`},
      {role:`S`, en:`100k units, reviewed each year.`, zh:`十万件，每年复核。`},
      {role:`B`, en:`Fair. Let's draft the agreement.`, zh:`合理，我们起草协议吧。`},
      {role:`S`, en:`I'll send the draft next week.`, zh:`我下周发草案。`},
    ],
    speak: [`We'd like to be your agent in Vietnam.`, `Do you have a showroom?`, `Let's draft the agreement.`],
    words: [
      {w:`agent`, ph:`/ˈeɪdʒənt/`, zh:`代理`},
      {w:`distributor`, ph:`/dɪˈstrɪbjətər/`, zh:`分销商`},
      {w:`exclusive`, ph:`/ɪkˈskluːsɪv/`, zh:`独家的`},
      {w:`coverage`, ph:`/ˈkʌvərɪdʒ/`, zh:`覆盖范围`},
      {w:`showroom`, ph:`/ˈʃoʊruːm/`, zh:`展厅`},
      {w:`target`, ph:`/ˈtɑːrɡɪt/`, zh:`目标`},
      {w:`annual`, ph:`/ˈænjuəl/`, zh:`年度的`},
      {w:`agreement`, ph:`/əˈɡriːmənt/`, zh:`协议`},
      {w:`draft`, ph:`/dræft/`, zh:`草案`},
      {w:`region`, ph:`/ˈriːdʒən/`, zh:`区域`},
      {w:`appoint`, ph:`/əˈpɔɪnt/`, zh:`委任`},
      {w:`territory`, ph:`/ˈterətɔːri/`, zh:`区域市场`},
    ]
  },
  { // 19 电话沟通与留言
    lines: [
      {role:`A`, en:`Hi, this is Wang from SunTech.`, zh:`您好，我是 SunTech 的王。`},
      {role:`B`, en:`Sorry, she's in a meeting.`, zh:`抱歉，她在开会。`},
      {role:`A`, en:`Could you take a message?`, zh:`能帮我留言吗？`},
      {role:`B`, en:`Sure, go ahead.`, zh:`可以，请讲。`},
      {role:`A`, en:`Ask her to call me about the shipment.`, zh:`请她回电，关于发货的事。`},
      {role:`B`, en:`Your number, please?`, zh:`您的号码是？`},
      {role:`A`, en:`138-0000-1234.`, zh:`138-0000-1234。`},
      {role:`B`, en:`Got it, I'll pass it on.`, zh:`记下了，我会转达。`},
      {role:`A`, en:`Thanks, by end of day if possible.`, zh:`谢谢，尽量今天内。`},
      {role:`B`, en:`Will do.`, zh:`会的。`},
    ],
    speak: [`This is Wang from SunTech.`, `Could you take a message?`, `Call me about the shipment.`],
    words: [
      {w:`call`, ph:`/kɔːl/`, zh:`电话`},
      {w:`message`, ph:`/ˈmesɪdʒ/`, zh:`留言`},
      {w:`voicemail`, ph:`/ˈvɔɪsmeɪl/`, zh:`语音信箱`},
      {w:`meeting`, ph:`/ˈmiːtɪŋ/`, zh:`会议`},
      {w:`number`, ph:`/ˈnʌmbər/`, zh:`号码`},
      {w:`pass on`, ph:`/pæs ɑːn/`, zh:`转达`},
      {w:`ring back`, ph:`/rɪŋ bæk/`, zh:`回电`},
      {w:`hold on`, ph:`/hoʊld ɑːn/`, zh:`稍等`},
      {w:`line`, ph:`/laɪn/`, zh:`线路`},
      {w:`busy`, ph:`/ˈbɪzi/`, zh:`占线`},
      {w:`transfer`, ph:`/trænsˈfɜːr/`, zh:`转接`},
      {w:`callback`, ph:`/ˈkɔːlbæk/`, zh:`回拨`},
    ]
  },
  { // 20 签约与后续合作
    lines: [
      {role:`A`, en:`Let's go through the contract clause by clause.`, zh:`我们逐条过一遍合同条款。`},
      {role:`B`, en:`Section 4, delivery: FOB Shenzhen.`, zh:`第 4 条，交货：深圳 FOB。`},
      {role:`A`, en:`Section 7, penalty for late delivery?`, zh:`第 7 条，延迟交货的罚则？`},
      {role:`B`, en:`0.5% per week, capped at 5%.`, zh:`每周 0.5%，上限 5%。`},
      {role:`A`, en:`Acceptable. Where do we sign?`, zh:`可以接受，在哪里签字？`},
      {role:`B`, en:`Here, and initial each page.`, zh:`这里，每页简签。`},
      {role:`A`, en:`Done. Shall we toast?`, zh:`签好了，干杯吗？`},
      {role:`B`, en:`To our long-term partnership!`, zh:`为我们长久的合作干杯！`},
      {role:`A`, en:`I'll kick off production next Monday.`, zh:`我下周一启动生产。`},
      {role:`B`, en:`And I'll release the deposit.`, zh:`我会放出定金。`},
    ],
    speak: [`Let's go through the contract clause by clause.`, `Penalty for late delivery?`, `To our long-term partnership!`],
    words: [
      {w:`contract`, ph:`/ˈkɑːntrækt/`, zh:`合同`},
      {w:`clause`, ph:`/klɔːz/`, zh:`条款`},
      {w:`sign`, ph:`/saɪn/`, zh:`签字`},
      {w:`initial`, ph:`/ɪˈnɪʃl/`, zh:`简签`},
      {w:`delivery`, ph:`/dɪˈlɪvəri/`, zh:`交付`},
      {w:`penalty`, ph:`/ˈpenəlti/`, zh:`罚则`},
      {w:`cap`, ph:`/kæp/`, zh:`上限`},
      {w:`partner`, ph:`/ˈpɑːrtnər/`, zh:`伙伴`},
      {w:`long-term`, ph:`/ˈlɔːŋ tɜːrm/`, zh:`长期的`},
      {w:`kick off`, ph:`/kɪk ɔːf/`, zh:`启动`},
      {w:`deposit`, ph:`/dɪˈpɑːzɪt/`, zh:`定金`},
      {w:`agreement`, ph:`/əˈɡriːmənt/`, zh:`协议`},
    ]
  },
];

const HEADER = `/* =========================================================
   旺仔的工作台 · 英语学习「听 / 说 / 单词」交互训练数据
   与 content.js 中 english 数组一一对应（索引 0-20）。
   每条：
     lines    听力对话 10 句（role + en + zh 中文翻译）
     speak    口语跟读 3 个目标句（数组）
     words    单词卡 12-15 个（w + ph + zh）
   说明：本文件不依赖任何外部库，配合 index.html 的 Web Speech API 使用。
   （每周焕新：本版为 2026-08-10 生成，21 天外贸/差旅/商务场景全新对话）
   ========================================================= */`;

let out = HEADER + `\nconst EN_PRACTICE = {\n`;
DAYS.forEach((d, i) => {
  out += `  ${i}: {\n`;
  out += `    lines: [\n`;
  d.lines.forEach(l => {
    out += `      {role:${JSON.stringify(l.role)}, en:${JSON.stringify(l.en)}, zh:${JSON.stringify(l.zh)}},\n`;
  });
  out += `    ],\n`;
  out += `    speak: [${d.speak.map(s => JSON.stringify(s)).join(', ')}],\n`;
  out += `    words: [\n`;
  d.words.forEach(w => {
    out += `      {w:${JSON.stringify(w.w)}, ph:${JSON.stringify(w.ph)}, zh:${JSON.stringify(w.zh)}},\n`;
  });
  out += `    ],\n`;
  out += `  },\n`;
});
out += `};\n`;

fs.writeFileSync('en_practice.js', out);
console.log('en_practice.js written, days:', DAYS.length, '| total words:', DAYS.reduce((a,d)=>a+d.words.length,0));
