/* =========================================================
   旺仔的工作台 · 英语学习「听 / 说 / 单词」交互训练数据
   与 content.js 中 english 数组一一对应（索引 0-20）。
   每条：
     lines    听力对话 10 句（role + en + zh 中文翻译）
     speak    口语跟读 3 个目标句（数组）
     words    单词卡 12-15 个（w + ph + zh）
   说明：本文件不依赖任何外部库，配合 index.html 的 Web Speech API 使用。
   ========================================================= */
const EN_PRACTICE = {
  0: {
    lines: [
      {role:"A", en:"May I see your passport, please?", zh:"请出示您的护照好吗？"},
      {role:"B", en:"Here you are.", zh:"给您。"},
      {role:"A", en:"Window or aisle seat?", zh:"靠窗还是靠走道的座位？"},
      {role:"B", en:"An aisle seat, please.", zh:"请给我靠走道的座位。"},
      {role:"A", en:"Your gate is B12. Have a nice flight!", zh:"您的登机口是 B12。祝您飞行愉快！"},
      {role:"B", en:"Where is the baggage claim?", zh:"行李提取处在哪里？"},
      {role:"A", en:"Carousel 5, downstairs.", zh:"5 号传送带，下楼就是。"},
      {role:"B", en:"How long is the layover?", zh:"中转停留多久？"},
      {role:"A", en:"About 90 minutes.", zh:"大约 90 分钟。"},
      {role:"B", en:"Great, plenty of time for coffee.", zh:"太好了，有足够的时间喝杯咖啡。"},
    ],
    speak: ["May I see your passport, please?", "Where is the baggage claim?", "How long is the layover?"],
    words: [
      {w:"passport", ph:"/ˈpæspɔːt/", zh:"护照"},
      {w:"ticket", ph:"/ˈtɪkɪt/", zh:"机票"},
      {w:"boarding pass", ph:"/ˈbɔːrdɪŋ pæs/", zh:"登机牌"},
      {w:"gate", ph:"/ɡeɪt/", zh:"登机口"},
      {w:"luggage", ph:"/ˈlʌɡɪdʒ/", zh:"行李"},
      {w:"departure", ph:"/dɪˈpɑːrtʃər/", zh:"出发"},
      {w:"arrival", ph:"/əˈraɪvl/", zh:"到达"},
      {w:"baggage claim", ph:"/ˈbæɡɪdʒ kleɪm/", zh:"行李提取处"},
      {w:"carousel", ph:"/kæˈruːsəl/", zh:"传送带"},
      {w:"terminal", ph:"/ˈtɜːrmɪnl/", zh:"航站楼"},
      {w:"layover", ph:"/ˈleɪoʊvər/", zh:"中转停留"},
      {w:"take off", ph:"/teɪk ɔːf/", zh:"起飞"},
      {w:"land", ph:"/lænd/", zh:"着陆"},
      {w:"window seat", ph:"/ˈwɪndoʊ siːt/", zh:"靠窗座位"},
    ]
  },
  1: {
    lines: [
      {role:"R", en:"Good evening, do you have a reservation?", zh:"晚上好，您有预订吗？"},
      {role:"G", en:"Yes, under the name Wang.", zh:"有，用 Wang 这个名字预订的。"},
      {role:"R", en:"Your room is 805. Here is your key card.", zh:"您的房间是 805。这是您的房卡。"},
      {role:"G", en:"What time is breakfast?", zh:"早餐几点供应？"},
      {role:"R", en:"7 to 10, on the second floor.", zh:"7 点到 10 点，在二楼。"},
      {role:"G", en:"Could I have a wake-up call at six?", zh:"能帮我定早上六点的叫早电话吗？"},
      {role:"R", en:"Sure, six sharp.", zh:"没问题，六点整。"},
      {role:"G", en:"What is the wifi password?", zh:"WiFi 密码是多少？"},
      {role:"R", en:"It is on your key card holder.", zh:"在您的房卡套上。"},
      {role:"G", en:"Thanks, I would like to check out tomorrow at noon.", zh:"谢谢，我想明天中午退房。"},
    ],
    speak: ["Do you have a reservation?", "What time is breakfast?", "Could I have a wake-up call?"],
    words: [
      {w:"reservation", ph:"/ˌrezərˈveɪʃn/", zh:"预订"},
      {w:"check in", ph:"/tʃek ɪn/", zh:"入住"},
      {w:"check out", ph:"/tʃek aʊt/", zh:"退房"},
      {w:"key card", ph:"/kiː kɑːrd/", zh:"房卡"},
      {w:"breakfast", ph:"/ˈbrekfəst/", zh:"早餐"},
      {w:"room service", ph:"/ruːm ˈsɜːrvɪs/", zh:"客房服务"},
      {w:"extra towel", ph:"/ˈekstrə ˈtaʊəl/", zh:"额外毛巾"},
      {w:"wifi password", ph:"/ˈwaɪfaɪ ˈpæswɜːrd/", zh:"无线密码"},
      {w:"wake-up call", ph:"/ˈweɪk ʌp kɔːl/", zh:"叫早电话"},
      {w:"lobby", ph:"/ˈlɑːbi/", zh:"大堂"},
      {w:"air conditioning", ph:"/er kənˈdɪʃənɪŋ/", zh:"空调"},
      {w:"single bed", ph:"/ˈsɪŋɡl bed/", zh:"单人床"},
      {w:"double bed", ph:"/ˈdʌbl bed/", zh:"双人床"},
      {w:"minibar", ph:"/ˈmɪnibɑːr/", zh:"迷你吧"},
    ]
  },
  2: {
    lines: [
      {role:"W", en:"Are you ready to order?", zh:"您准备好点餐了吗？"},
      {role:"G", en:"What do you recommend?", zh:"您推荐什么？"},
      {role:"W", en:"The grilled fish is popular.", zh:"烤鱼很受欢迎。"},
      {role:"G", en:"I will have that, medium, no spice.", zh:"我要那份，五分熟，不要辣。"},
      {role:"W", en:"Sure. Anything to drink?", zh:"好的。喝点什么？"},
      {role:"G", en:"A glass of water, please.", zh:"请给我一杯水。"},
      {role:"W", en:"Are you allergic to anything?", zh:"您对什么过敏吗？"},
      {role:"G", en:"Yes, peanuts. Please avoid them.", zh:"对，花生。请避开它。"},
      {role:"W", en:"Got it. Dessert today is cheesecake.", zh:"明白了。今天的甜点是芝士蛋糕。"},
      {role:"G", en:"Could we have the bill, please?", zh:"麻烦给我们账单好吗？"},
    ],
    speak: ["What do you recommend?", "I am allergic to peanuts.", "Could we have the bill?"],
    words: [
      {w:"menu", ph:"/ˈmenjuː/", zh:"菜单"},
      {w:"order", ph:"/ˈɔːrdər/", zh:"点餐"},
      {w:"recommend", ph:"/ˌrekəˈmend/", zh:"推荐"},
      {w:"spicy", ph:"/ˈspaɪsi/", zh:"辣的"},
      {w:"well done", ph:"/wel dʌn/", zh:"全熟"},
      {w:"medium", ph:"/ˈmiːdiəm/", zh:"五分熟"},
      {w:"the bill", ph:"/ðə bɪl/", zh:"账单"},
      {w:"tip", ph:"/tɪp/", zh:"小费"},
      {w:"appetizer", ph:"/ˈæpɪtaɪzər/", zh:"前菜"},
      {w:"dessert", ph:"/dɪˈzɜːrt/", zh:"甜点"},
      {w:"allergy", ph:"/ˈælərdʒi/", zh:"过敏"},
      {w:"takeaway", ph:"/ˈteɪkəweɪ/", zh:"外带"},
      {w:"table for two", ph:"/ˈteɪbl fɔːr tuː/", zh:"两人桌"},
      {w:"split the bill", ph:"/splɪt ðə bɪl/", zh:"AA 账单"},
    ]
  },
  3: {
    lines: [
      {role:"T", en:"Excuse me, how do I get to the station?", zh:"打扰一下，去车站怎么走？"},
      {role:"P", en:"Go straight, then turn left at the bank.", zh:"直走，然后在银行处左转。"},
      {role:"T", en:"Is it far?", zh:"远吗？"},
      {role:"P", en:"No, about five minutes on foot.", zh:"不远，步行大约五分钟。"},
      {role:"T", en:"Is there a bus stop nearby?", zh:"附近有公交站吗？"},
      {role:"P", en:"Yes, just across the street.", zh:"有，就在街对面。"},
      {role:"T", en:"Which bus goes to the museum?", zh:"哪路公交去博物馆？"},
      {role:"P", en:"Bus 24, but a taxi is faster.", zh:"24 路，不过打车更快。"},
      {role:"T", en:"How long does it take by taxi?", zh:"打车要多久？"},
      {role:"P", en:"Around ten minutes if traffic is light.", zh:"如果路况顺畅，大约十分钟。"},
    ],
    speak: ["How do I get to the station?", "Is it far from here?", "How long does it take?"],
    words: [
      {w:"subway", ph:"/ˈsʌbweɪ/", zh:"地铁"},
      {w:"bus stop", ph:"/bʌs stɑːp/", zh:"公交站"},
      {w:"crossroad", ph:"/ˈkrɔːsroʊd/", zh:"十字路口"},
      {w:"turn left", ph:"/tɜːrn left/", zh:"左转"},
      {w:"turn right", ph:"/tɜːrn raɪt/", zh:"右转"},
      {w:"straight", ph:"/streɪt/", zh:"直走"},
      {w:"opposite", ph:"/ˈɑːpəzɪt/", zh:"对面"},
      {w:"taxi", ph:"/ˈtæksi/", zh:"出租车"},
      {w:"address", ph:"/əˈdres/", zh:"地址"},
      {w:"traffic light", ph:"/ˈtræfɪk laɪt/", zh:"红绿灯"},
      {w:"block", ph:"/blɑːk/", zh:"街区"},
      {w:"sidewalk", ph:"/ˈsaɪdwɔːk/", zh:"人行道"},
      {w:"on foot", ph:"/ɑːn fʊt/", zh:"步行"},
      {w:"traffic", ph:"/ˈtræfɪk/", zh:"交通"},
    ]
  },
  4: {
    lines: [
      {role:"S", en:"Can I help you?", zh:"需要帮忙吗？"},
      {role:"G", en:"How much is this T-shirt?", zh:"这件 T 恤多少钱？"},
      {role:"S", en:"25 dollars.", zh:"25 美元。"},
      {role:"G", en:"That is a bit much. Can you give a discount?", zh:"有点贵。能打折吗？"},
      {role:"S", en:"OK, 20 for you.", zh:"行，20 给您。"},
      {role:"G", en:"Do you have a smaller size?", zh:"有更小号的吗？"},
      {role:"S", en:"Let me check. Yes, medium fits.", zh:"我查一下。有，中号合适。"},
      {role:"G", en:"May I try it on?", zh:"我可以试穿吗？"},
      {role:"S", en:"Sure, fitting room is on your left.", zh:"当然，试衣间在您左边。"},
      {role:"G", en:"I will take it. Card, please.", zh:"我要了。请刷卡。"},
    ],
    speak: ["Can you give a discount?", "Do you have a smaller size?", "Can I try this on?"],
    words: [
      {w:"price", ph:"/praɪs/", zh:"价格"},
      {w:"discount", ph:"/ˈdɪskaʊnt/", zh:"折扣"},
      {w:"cash", ph:"/kæʃ/", zh:"现金"},
      {w:"card", ph:"/kɑːrd/", zh:"刷卡"},
      {w:"size", ph:"/saɪz/", zh:"尺码"},
      {w:"receipt", ph:"/rɪˈsiːt/", zh:"收据"},
      {w:"try on", ph:"/traɪ ɑːn/", zh:"试穿"},
      {w:"fitting room", ph:"/ˈfɪtɪŋ ruːm/", zh:"试衣间"},
      {w:"color", ph:"/ˈkʌlər/", zh:"颜色"},
      {w:"refund", ph:"/ˈriːfʌnd/", zh:"退款"},
      {w:"exchange", ph:"/ɪksˈtʃeɪndʒ/", zh:"换货"},
      {w:"on sale", ph:"/ɑːn seɪl/", zh:"打折中"},
      {w:"checkout", ph:"/ˈtʃekaʊt/", zh:"结账"},
      {w:"shop assistant", ph:"/ʃɑːp əˈsɪstənt/", zh:"店员"},
    ]
  },
  5: {
    lines: [
      {role:"G", en:"Excuse me, I lost my wallet.", zh:"打扰一下，我的钱包丢了。"},
      {role:"P", en:"Stay calm. Did you call the police?", zh:"保持冷静。您报警了吗？"},
      {role:"G", en:"Not yet. Can you help me?", zh:"还没。能帮我吗？"},
      {role:"P", en:"Sure, let us go to the station together.", zh:"当然，我们一起去警局。"},
      {role:"G", en:"I also have a high fever. Can I see a doctor?", zh:"我还发高烧。能看医生吗？"},
      {role:"P", en:"There is a hospital two blocks away.", zh:"两个街区外有家医院。"},
      {role:"G", en:"Please call an ambulance.", zh:"请叫辆救护车。"},
      {role:"P", en:"Ambulance is on the way, five minutes.", zh:"救护车已在路上，五分钟到。"},
      {role:"G", en:"My passport was stolen. Where is the embassy?", zh:"我的护照被偷了。大使馆在哪里？"},
      {role:"P", en:"I will call them and explain your situation.", zh:"我打电话给他们说明您的情况。"},
    ],
    speak: ["I lost my wallet.", "Please call an ambulance.", "I need to see a doctor."],
    words: [
      {w:"help", ph:"/help/", zh:"帮助"},
      {w:"lost", ph:"/lɔːst/", zh:"迷路/丢失"},
      {w:"emergency", ph:"/ɪˈmɜːrdʒənsi/", zh:"紧急情况"},
      {w:"hospital", ph:"/ˈhɑːspɪtl/", zh:"医院"},
      {w:"police", ph:"/pəˈliːs/", zh:"警察"},
      {w:"medicine", ph:"/ˈmedɪsn/", zh:"药"},
      {w:"insurance", ph:"/ɪnˈʃʊrəns/", zh:"保险"},
      {w:"ambulance", ph:"/ˈæmbjələns/", zh:"救护车"},
      {w:"fever", ph:"/ˈfiːvər/", zh:"发烧"},
      {w:"pain", ph:"/peɪn/", zh:"疼痛"},
      {w:"embassy", ph:"/ˈembəsi/", zh:"大使馆"},
      {w:"stolen", ph:"/ˈstoʊlən/", zh:"被偷"},
      {w:"first aid", ph:"/fɜːrst eɪd/", zh:"急救"},
      {w:"pharmacy", ph:"/ˈfɑːrməsi/", zh:"药店"},
    ]
  },
  6: {
    lines: [
      {role:"A", en:"Good morning. Here is your boarding pass.", zh:"早上好。这是您的登机牌。"},
      {role:"B", en:"Thank you. Where is gate B12?", zh:"谢谢。B12 登机口在哪里？"},
      {role:"A", en:"Go straight, then turn left.", zh:"直走，然后左转。"},
      {role:"B", en:"Got it. And breakfast?", zh:"明白了。那早餐呢？"},
      {role:"A", en:"The hotel serves it from 7.", zh:"酒店从 7 点开始供应。"},
      {role:"B", en:"Could I have a wake-up call at six?", zh:"能帮我定六点的叫早吗？"},
      {role:"A", en:"Sure, six sharp.", zh:"没问题，六点整。"},
      {role:"B", en:"What time is checkout?", zh:"几点退房？"},
      {role:"A", en:"Noon. Enjoy your stay.", zh:"中午。祝您住得愉快。"},
      {role:"B", en:"Thanks, I would like the bill now.", zh:"谢谢，我现在要账单。"},
    ],
    speak: ["Where is gate B12?", "Could I have a wake-up call?", "I would like the bill now."],
    words: [
      {w:"passport", ph:"/ˈpæspɔːt/", zh:"护照"},
      {w:"boarding pass", ph:"/ˈbɔːrdɪŋ pæs/", zh:"登机牌"},
      {w:"gate", ph:"/ɡeɪt/", zh:"登机口"},
      {w:"reservation", ph:"/ˌrezərˈveɪʃn/", zh:"预订"},
      {w:"menu", ph:"/ˈmenjuː/", zh:"菜单"},
      {w:"discount", ph:"/ˈdɪskaʊnt/", zh:"折扣"},
      {w:"help", ph:"/help/", zh:"帮助"},
      {w:"wake-up call", ph:"/ˈweɪk ʌp kɔːl/", zh:"叫早"},
      {w:"checkout", ph:"/ˈtʃekaʊt/", zh:"退房"},
      {w:"bill", ph:"/bɪl/", zh:"账单"},
      {w:"straight", ph:"/streɪt/", zh:"直走"},
      {w:"turn left", ph:"/tɜːrn left/", zh:"左转"},
      {w:"recommend", ph:"/ˌrekəˈmend/", zh:"推荐"},
      {w:"noon", ph:"/nuːn/", zh:"中午"},
    ]
  },
  7: {
    lines: [
      {role:"R", en:"Hello, ABC Company, how may I help?", zh:"您好，ABC 公司，有什么可以帮您？"},
      {role:"W", en:"This is Wang. I would like to book a meeting on Friday.", zh:"我是 Wang。我想预约周五的会议。"},
      {role:"R", en:"10 a.m. is available. Shall I confirm?", zh:"上午 10 点有空。要我确认吗？"},
      {role:"W", en:"Yes, please. Thank you.", zh:"好的，麻烦了。谢谢。"},
      {role:"R", en:"May I have your callback number?", zh:"能留个回电号码吗？"},
      {role:"W", en:"Sure, 555-0188.", zh:"当然，555-0188。"},
      {role:"R", en:"Could you put me on hold for a moment?", zh:"能让我稍等一下吗？"},
      {role:"W", en:"Of course, take your time.", zh:"当然，您慢慢来。"},
      {role:"R", en:"Sorry, the line was busy.", zh:"抱歉，刚才线路忙。"},
      {role:"W", en:"No problem, please leave a message.", zh:"没关系，请留言。"},
    ],
    speak: ["This is Wang. I would like to book a meeting.", "Could you put me on hold?", "May I leave a message?"],
    words: [
      {w:"appointment", ph:"/əˈpɔɪntmənt/", zh:"预约"},
      {w:"available", ph:"/əˈveɪləbl/", zh:"有空的"},
      {w:"call back", ph:"/kɔːl bæk/", zh:"回电"},
      {w:"message", ph:"/ˈmesɪdʒ/", zh:"留言"},
      {w:"confirm", ph:"/kənˈfɜːrm/", zh:"确认"},
      {w:"reschedule", ph:"/riːˈskedʒuːl/", zh:"改期"},
      {w:"extension", ph:"/ɪkˈstenʃn/", zh:"分机"},
      {w:"voicemail", ph:"/ˈvɔɪsmeɪl/", zh:"语音信箱"},
      {w:"hold on", ph:"/hoʊld ɑːn/", zh:"稍等"},
      {w:"wrong number", ph:"/rɔːŋ ˈnʌmbər/", zh:"错号"},
      {w:"operator", ph:"/ˈɑːpəreɪtər/", zh:"接线员"},
      {w:"dial", ph:"/ˈdaɪəl/", zh:"拨号"},
      {w:"busy line", ph:"/ˈbɪzi laɪn/", zh:"占线"},
      {w:"landline", ph:"/ˈlændlaɪn/", zh:"座机"},
    ]
  },
  8: {
    lines: [
      {role:"W", en:"Dear Mr. Smith, I am writing to confirm our meeting at 10 a.m. on Friday.", zh:"尊敬的 Smith 先生，我写此信确认我们周五上午 10 点的会议。"},
      {role:"W", en:"Please find the agenda in the attachment.", zh:"请在附件中查收议程。"},
      {role:"W", en:"Kindly let me know if the time works for you.", zh:"烦请告知该时间对您是否合适。"},
      {role:"W", en:"Best regards, Wang.", zh:"此致敬礼，Wang。"},
      {role:"W", en:"Could you please reply by Thursday noon?", zh:"能否在周四中午前回复？"},
      {role:"W", en:"I have also copied our manager on this email.", zh:"我也把这封邮件抄送给了我们的经理。"},
      {role:"W", en:"Looking forward to our discussion.", zh:"期待我们的讨论。"},
      {role:"W", en:"Please let me know if you have any questions.", zh:"如有任何问题请告知。"},
      {role:"W", en:"Feel free to suggest a better time.", zh:"欢迎您提出更合适的时间。"},
      {role:"W", en:"Thank you for your time and consideration.", zh:"感谢您的时间与考虑。"},
    ],
    speak: ["I am writing to confirm our meeting.", "Please find the agenda attached.", "Could you kindly reply by Friday?"],
    words: [
      {w:"subject", ph:"/ˈsʌbdʒɪkt/", zh:"主题"},
      {w:"attachment", ph:"/əˈtætʃmənt/", zh:"附件"},
      {w:"regards", ph:"/rɪˈɡɑːrdz/", zh:"此致敬礼"},
      {w:"deadline", ph:"/ˈdedlaɪn/", zh:"截止日"},
      {w:"follow up", ph:"/ˈfɑːloʊ ʌp/", zh:"跟进"},
      {w:"apologize", ph:"/əˈpɑːlədʒaɪz/", zh:"致歉"},
      {w:"kindly", ph:"/ˈkaɪndli/", zh:"劳烦"},
      {w:"cc", ph:"/siː siː/", zh:"抄送"},
      {w:"bcc", ph:"/biː siː siː/", zh:"密送"},
      {w:"signature", ph:"/ˈsɪɡnətʃər/", zh:"签名"},
      {w:"recipient", ph:"/rɪˈsɪpiənt/", zh:"收件人"},
      {w:"urgent", ph:"/ˈɜːrdʒənt/", zh:"紧急"},
      {w:"inquiry", ph:"/ɪnˈkwaɪəri/", zh:"询问"},
      {w:"reply", ph:"/rɪˈplaɪ/", zh:"回复"},
    ]
  },
  9: {
    lines: [
      {role:"A", en:"Let me introduce myself. I am Wang from the sales team.", zh:"让我自我介绍一下。我是销售团队的 Wang。"},
      {role:"B", en:"Nice to meet you, Wang. I handle marketing.", zh:"很高兴认识你，Wang。我负责市场。"},
      {role:"A", en:"Pleased to meet you. Hope we can work together.", zh:"幸会。希望我们能一起共事。"},
      {role:"A", en:"I am responsible for the Asia-Pacific region.", zh:"我负责亚太地区。"},
      {role:"B", en:"Great, my background is in product design.", zh:"太好了，我的背景是产品设计。"},
      {role:"A", en:"How long have you been with the company?", zh:"你在这家公司多久了？"},
      {role:"B", en:"Five years. I joined right after graduation.", zh:"五年了。我毕业后就加入了。"},
      {role:"A", en:"Impressive. What are you in charge of now?", zh:"真不错。你现在负责什么？"},
      {role:"B", en:"I lead the user research team.", zh:"我带领用户研究团队。"},
      {role:"A", en:"I look forward to collaborating with you.", zh:"期待与您合作。"},
    ],
    speak: ["I am Wang from the sales team.", "Let me introduce myself.", "I look forward to working with you."],
    words: [
      {w:"introduce", ph:"/ˌɪntrəˈdjuːs/", zh:"介绍"},
      {w:"responsibility", ph:"/rɪˌspɑːnsəˈbɪləti/", zh:"职责"},
      {w:"team", ph:"/tiːm/", zh:"团队"},
      {w:"project", ph:"/ˈprɑːdʒekt/", zh:"项目"},
      {w:"in charge of", ph:"/ɪn tʃɑːrdʒ ʌv/", zh:"负责"},
      {w:"pleased", ph:"/pliːzd/", zh:"荣幸"},
      {w:"colleague", ph:"/ˈkɑːliːɡ/", zh:"同事"},
      {w:"department", ph:"/dɪˈpɑːrtmənt/", zh:"部门"},
      {w:"position", ph:"/pəˈzɪʃn/", zh:"职位"},
      {w:"background", ph:"/ˈbækɡraʊnd/", zh:"背景"},
      {w:"experience", ph:"/ɪkˈspɪriəns/", zh:"经验"},
      {w:"graduation", ph:"/ˌɡrædʒuˈeɪʃn/", zh:"毕业"},
      {w:"collaborate", ph:"/kəˈlæbəreɪt/", zh:"合作"},
      {w:"region", ph:"/ˈriːdʒən/", zh:"区域"},
    ]
  },
  10: {
    lines: [
      {role:"H", en:"Welcome to our city! Please try the local specialty.", zh:"欢迎来到我们城市！请尝尝当地特色菜。"},
      {role:"G", en:"Thank you, it is delicious.", zh:"谢谢，很好吃。"},
      {role:"H", en:"Let us toast to our cooperation.", zh:"为我们的合作干杯。"},
      {role:"G", en:"Cheers! I look forward to working with you.", zh:"干杯！期待与您共事。"},
      {role:"H", en:"Please help yourself to the seafood.", zh:"请随意享用海鲜。"},
      {role:"G", en:"The wine is wonderful. What is it?", zh:"这酒很棒。是什么酒？"},
      {role:"H", en:"A local vintage from 2018.", zh:"2018 年的本地年份酒。"},
      {role:"G", en:"I am honored by your hospitality.", zh:"您的款待让我倍感荣幸。"},
      {role:"H", en:"It is our pleasure. Enjoy the evening.", zh:"这是我们的荣幸。祝您度过美好的夜晚。"},
      {role:"G", en:"Could we have the bill, please?", zh:"麻烦给我们账单好吗？"},
    ],
    speak: ["Let us toast to our cooperation.", "Please help yourself.", "It was a wonderful evening."],
    words: [
      {w:"host", ph:"/hoʊst/", zh:"招待"},
      {w:"toast", ph:"/toʊst/", zh:"祝酒"},
      {w:"specialty", ph:"/ˈspeʃəlti/", zh:"特色菜"},
      {w:"honor", ph:"/ˈɑːnər/", zh:"荣幸"},
      {w:"cooperation", ph:"/koʊˌɑːpəˈreɪʃn/", zh:"合作"},
      {w:"enjoy", ph:"/ɪnˈdʒɔɪ/", zh:"享用"},
      {w:"delicious", ph:"/dɪˈlɪʃəs/", zh:"美味"},
      {w:"appetizer", ph:"/ˈæpɪtaɪzər/", zh:"前菜"},
      {w:"seafood", ph:"/ˈsiːfuːd/", zh:"海鲜"},
      {w:"vintage", ph:"/ˈvɪntɪdʒ/", zh:"年份酒"},
      {w:"hospitality", ph:"/ˌhɑːspɪˈtæləti/", zh:"款待"},
      {w:"cheers", ph:"/tʃɪrz/", zh:"干杯"},
      {w:"main course", ph:"/meɪn kɔːrs/", zh:"主菜"},
      {w:"the bill", ph:"/ðə bɪl/", zh:"账单"},
    ]
  },
  11: {
    lines: [
      {role:"W", en:"I would like to submit my travel expenses.", zh:"我想提交我的差旅费报销。"},
      {role:"F", en:"Sure, do you have all the receipts?", zh:"好的，您有所有发票吗？"},
      {role:"W", en:"Yes, taxi, hotel and meals.", zh:"有，打车、酒店和餐费。"},
      {role:"F", en:"Great, I will forward it for approval.", zh:"好的，我会转交审批。"},
      {role:"W", en:"What is the per diem limit?", zh:"每日补贴上限是多少？"},
      {role:"F", en:"100 dollars per day for meals.", zh:"餐费每天 100 美元。"},
      {role:"W", en:"Should I include taxi mileage?", zh:"我要把打车里程也算进去吗？"},
      {role:"F", en:"Yes, please itemize everything.", zh:"是的，请把每一项都列清楚。"},
      {role:"W", en:"When will it be reimbursed?", zh:"什么时候能报销下来？"},
      {role:"F", en:"Within five business days.", zh:"五个工作日内。"},
    ],
    speak: ["I would like to submit my travel expenses.", "Please keep all receipts.", "When will it be reimbursed?"],
    words: [
      {w:"expense", ph:"/ɪkˈspens/", zh:"费用"},
      {w:"reimburse", ph:"/ˌriːɪmˈbɜːrs/", zh:"报销"},
      {w:"receipt", ph:"/rɪˈsiːt/", zh:"发票"},
      {w:"claim", ph:"/kleɪm/", zh:"申领"},
      {w:"budget", ph:"/ˈbʌdʒɪt/", zh:"预算"},
      {w:"approve", ph:"/əˈpruːv/", zh:"批准"},
      {w:"submit", ph:"/səbˈmɪt/", zh:"提交"},
      {w:"per diem", ph:"/pər ˈdiːəm/", zh:"每日补贴"},
      {w:"allowance", ph:"/əˈlaʊəns/", zh:"津贴"},
      {w:"advance", ph:"/ədˈvæns/", zh:"预支"},
      {w:"mileage", ph:"/ˈmaɪlɪdʒ/", zh:"里程"},
      {w:"itemize", ph:"/ˈaɪtəmaɪz/", zh:"分项列出"},
      {w:"currency", ph:"/ˈkɜːrənsi/", zh:"货币"},
      {w:"exchange rate", ph:"/ɪksˈtʃeɪndʒ reɪt/", zh:"汇率"},
    ]
  },
  12: {
    lines: [
      {role:"A", en:"I think we should launch in June.", zh:"我认为我们应该在六月推出。"},
      {role:"B", en:"I see it differently. Perhaps September is safer.", zh:"我看法不同。也许九月更稳妥。"},
      {role:"A", en:"Good point. Let us consider both.", zh:"说得对。我们把两个都考虑一下。"},
      {role:"A", en:"In my opinion, the market is ready now.", zh:"在我看来，市场现在已就绪。"},
      {role:"B", en:"I disagree. The data shows risk in Q2.", zh:"我不同意。数据显示第二季度有风险。"},
      {role:"A", en:"Fair point, but we cannot wait forever.", zh:"说得在理，但我们不能一直等。"},
      {role:"B", en:"On the other hand, rushing is risky.", zh:"另一方面，操之过急也有风险。"},
      {role:"A", en:"Let us compromise on August.", zh:"我们就折中定在八月吧。"},
      {role:"B", en:"That sounds reasonable. I can agree.", zh:"听起来合理。我可以同意。"},
      {role:"A", en:"Great, we will finalize next week.", zh:"很好，我们下周敲定。"},
    ],
    speak: ["I see it differently.", "In my opinion, we should wait.", "Fair point, but consider the cost."],
    words: [
      {w:"agree", ph:"/əˈɡriː/", zh:"同意"},
      {w:"disagree", ph:"/ˌdɪsəˈɡriː/", zh:"不同意"},
      {w:"opinion", ph:"/əˈpɪnjən/", zh:"观点"},
      {w:"suggest", ph:"/səˈdʒest/", zh:"建议"},
      {w:"perhaps", ph:"/pərˈhæps/", zh:"也许"},
      {w:"however", ph:"/haʊˈevər/", zh:"然而"},
      {w:"consider", ph:"/kənˈsɪdər/", zh:"考虑"},
      {w:"point of view", ph:"/pɔɪnt əv vjuː/", zh:"观点"},
      {w:"on the other hand", ph:"/ɑːn ðə ˈʌðər hænd/", zh:"另一方面"},
      {w:"compromise", ph:"/ˈkɑːmprəmaɪz/", zh:"妥协"},
      {w:"reasonable", ph:"/ˈriːznəbəl/", zh:"合理"},
      {w:"risk", ph:"/rɪsk/", zh:"风险"},
      {w:"finalize", ph:"/ˈfaɪnəlaɪz/", zh:"敲定"},
    ]
  },
  13: {
    lines: [
      {role:"A", en:"Let me start the meeting. I am Wang from sales.", zh:"我来主持会议。我是销售的 Wang。"},
      {role:"B", en:"Nice to meet you. I handle marketing.", zh:"很高兴认识你。我负责市场。"},
      {role:"A", en:"I am writing to confirm our plan.", zh:"我写此信确认我们的计划。"},
      {role:"B", en:"Good. Let us toast to cooperation.", zh:"好。为合作干杯。"},
      {role:"A", en:"Could we reschedule the call to Friday?", zh:"能把通话改到周五吗？"},
      {role:"B", en:"Sure, Friday 10 a.m. works for me.", zh:"当然，周五上午 10 点对我可以。"},
      {role:"A", en:"Please find the agenda attached.", zh:"请在附件中查收议程。"},
      {role:"B", en:"Got it. I will reply by tomorrow.", zh:"收到。我明天前回复。"},
      {role:"A", en:"Let us submit the expense report today.", zh:"我们今天提交费用报告吧。"},
      {role:"B", en:"I agree, let us finalize it now.", zh:"我同意，现在就敲定。"},
    ],
    speak: ["Let me start the meeting.", "I am writing to confirm our plan.", "Let us toast to cooperation."],
    words: [
      {w:"appointment", ph:"/əˈpɔɪntmənt/", zh:"预约"},
      {w:"attachment", ph:"/əˈtætʃmənt/", zh:"附件"},
      {w:"introduce", ph:"/ˌɪntrəˈdjuːs/", zh:"介绍"},
      {w:"toast", ph:"/toʊst/", zh:"祝酒"},
      {w:"expense", ph:"/ɪkˈspens/", zh:"费用"},
      {w:"agree", ph:"/əˈɡriː/", zh:"同意"},
      {w:"reschedule", ph:"/riːˈskedʒuːl/", zh:"改期"},
      {w:"submit", ph:"/səbˈmɪt/", zh:"提交"},
      {w:"agenda", ph:"/əˈdʒendə/", zh:"议程"},
      {w:"reply", ph:"/rɪˈplaɪ/", zh:"回复"},
      {w:"deadline", ph:"/ˈdedlaɪn/", zh:"截止日"},
      {w:"cooperation", ph:"/koʊˌɑːpəˈreɪʃn/", zh:"合作"},
      {w:"finalize", ph:"/ˈfaɪnəlaɪz/", zh:"敲定"},
      {w:"follow up", ph:"/ˈfɑːloʊ ʌp/", zh:"跟进"},
    ]
  },
  14: {
    lines: [
      {role:"B", en:"Our quote is 10,000 dollars.", zh:"我们报价 10,000 美元。"},
      {role:"S", en:"That is above our budget. Can you do better?", zh:"这超出了我们的预算。能再优惠些吗？"},
      {role:"B", en:"For a long-term deal, I can offer 5 percent off.", zh:"如果是长期合作，我可以给 5% 折扣。"},
      {role:"S", en:"Accepted. Let us finalize the terms.", zh:"成交。我们来敲定条款吧。"},
      {role:"S", en:"What about the payment terms?", zh:"付款条款呢？"},
      {role:"B", en:"Net 30 days, bank transfer is fine.", zh:"30 天净期，银行转账即可。"},
      {role:"S", en:"Could we split the difference on shipping?", zh:"运费我们能否各让一半？"},
      {role:"B", en:"Agreed, we split 50-50.", zh:"同意，我们五五分。"},
      {role:"S", en:"When can we sign the contract?", zh:"我们什么时候签合同？"},
      {role:"B", en:"This Friday. We have a win-win deal.", zh:"这周五。我们达成了双赢交易。"},
    ],
    speak: ["Can you do better on price?", "Let us finalize the terms.", "Could we split the difference?"],
    words: [
      {w:"quote", ph:"/kwoʊt/", zh:"报价"},
      {w:"negotiate", ph:"/nɪˈɡoʊʃieɪt/", zh:"谈判"},
      {w:"discount", ph:"/ˈdɪskaʊnt/", zh:"折扣"},
      {w:"final offer", ph:"/ˈfaɪnl ˈɔːfər/", zh:"最终价"},
      {w:"win-win", ph:"/wɪn wɪn/", zh:"双赢"},
      {w:"terms", ph:"/tɜːrmz/", zh:"条款"},
      {w:"deal", ph:"/diːl/", zh:"交易"},
      {w:"counter offer", ph:"/ˈkaʊntər ˈɔːfər/", zh:"还价"},
      {w:"contract", ph:"/ˈkɑːntrækt/", zh:"合同"},
      {w:"sign", ph:"/saɪn/", zh:"签署"},
      {w:"payment terms", ph:"/ˈpeɪmənt tɜːrmz/", zh:"付款条款"},
      {w:"split the difference", ph:"/splɪt ðə ˈdɪfrəns/", zh:"折中"},
      {w:"vendor", ph:"/ˈvendər/", zh:"供应商"},
      {w:"budget", ph:"/ˈbʌdʒɪt/", zh:"预算"},
    ]
  },
  15: {
    lines: [
      {role:"W", en:"Good morning. Today I will cover three points about our plan.", zh:"早上好。今天我将讲我们计划的三点内容。"},
      {role:"W", en:"First, the market. As the chart shows, demand is rising.", zh:"首先，市场。如图表所示，需求正在上升。"},
      {role:"W", en:"Let me highlight the key point. We must move fast.", zh:"我来强调关键点。我们必须快速行动。"},
      {role:"W", en:"Any questions?", zh:"有什么问题吗？"},
      {role:"A", en:"What is our target market?", zh:"我们的目标市场是什么？"},
      {role:"W", en:"Mid-size companies in Southeast Asia.", zh:"东南亚的中型企业。"},
      {role:"A", en:"How big is the addressable market?", zh:"可触达市场规模有多大？"},
      {role:"W", en:"Around two billion dollars by 2028.", zh:"到 2028 年约 20 亿美元。"},
      {role:"A", en:"What is the timeline?", zh:"时间线是怎样的？"},
      {role:"W", en:"Six months. In summary, now is the time to act.", zh:"六个月。总之，现在是行动的时候了。"},
    ],
    speak: ["Today I will cover three points about our plan.", "Let me highlight the key point.", "Any questions so far?"],
    words: [
      {w:"present", ph:"/prɪˈzent/", zh:"演示"},
      {w:"chart", ph:"/tʃɑːrt/", zh:"图表"},
      {w:"highlight", ph:"/ˈhaɪlaɪt/", zh:"强调"},
      {w:"key point", ph:"/kiː pɔɪnt/", zh:"要点"},
      {w:"summary", ph:"/ˈsʌməri/", zh:"总结"},
      {w:"question", ph:"/ˈkwestʃən/", zh:"提问"},
      {w:"feedback", ph:"/ˈfiːdbæk/", zh:"反馈"},
      {w:"overview", ph:"/ˈoʊvərvjuː/", zh:"概览"},
      {w:"statistic", ph:"/stəˈtɪstɪk/", zh:"数据"},
      {w:"trend", ph:"/trend/", zh:"趋势"},
      {w:"conclusion", ph:"/kənˈkluːʒn/", zh:"结论"},
      {w:"timeline", ph:"/ˈtaɪmlaɪn/", zh:"时间线"},
      {w:"target market", ph:"/ˈtɑːrɡɪt ˈmɑːrkɪt/", zh:"目标市场"},
      {w:"objective", ph:"/əbˈdʒektɪv/", zh:"目标"},
    ]
  },
  16: {
    lines: [
      {role:"W", en:"Can everyone hear me? Good. Let us start with the agenda.", zh:"大家都能听到我吗？好。我们按议程开始。"},
      {role:"L", en:"Your action item was the report. Status?", zh:"你的待办是那份报告。进度如何？"},
      {role:"W", en:"Done, I will send the minutes after.", zh:"完成了，会后我会发纪要。"},
      {role:"W", en:"Great, I will delegate the follow-up to Tom.", zh:"好的，我会把跟进工作委派给 Tom。"},
      {role:"L", en:"Could you put yourself on mute?", zh:"能请您静音吗？"},
      {role:"W", en:"Sorry, done.", zh:"抱歉，好了。"},
      {role:"L", en:"Let us share the screen now.", zh:"我们现在共享屏幕吧。"},
      {role:"W", en:"Can everyone see the chart?", zh:"大家都能看到图表吗？"},
      {role:"L", en:"Yes, please raise your hand for questions.", zh:"能，有问题请举手。"},
      {role:"W", en:"Any other questions before we close?", zh:"结束前还有其他问题吗？"},
    ],
    speak: ["Can everyone hear me?", "Could you put yourself on mute?", "I will send the minutes after."],
    words: [
      {w:"mute", ph:"/mjuːt/", zh:"静音"},
      {w:"signal", ph:"/ˈsɪɡnəl/", zh:"信号"},
      {w:"agenda", ph:"/əˈdʒendə/", zh:"议程"},
      {w:"action item", ph:"/ˈækʃn ˈaɪtəm/", zh:"待办"},
      {w:"minutes", ph:"/ˈmɪnɪts/", zh:"纪要"},
      {w:"follow up", ph:"/ˈfɑːloʊ ʌp/", zh:"跟进"},
      {w:"delegate", ph:"/ˈdelɪɡeɪt/", zh:"委派"},
      {w:"dial in", ph:"/ˈdaɪəl ɪn/", zh:"拨入"},
      {w:"screen share", ph:"/skriːn ʃer/", zh:"屏幕共享"},
      {w:"raise hand", ph:"/reɪz hænd/", zh:"举手"},
      {w:"breakout", ph:"/ˈbreɪkaʊt/", zh:"分组讨论"},
      {w:"host", ph:"/hoʊst/", zh:"主持人"},
      {w:"chat", ph:"/tʃæt/", zh:"文字聊天"},
      {w:"unmute", ph:"/ʌnˈmjuːt/", zh:"取消静音"},
    ]
  },
  17: {
    lines: [
      {role:"W", en:"Mr. Smith, welcome! You must be tired from the flight.", zh:"Smith 先生，欢迎！您坐飞机一定累了吧。"},
      {role:"S", en:"A little, thank you.", zh:"有一点，谢谢。"},
      {role:"W", en:"The car is outside. We arranged a hotel near the office.", zh:"车在外面。我们安排了离办公室很近的酒店。"},
      {role:"W", en:"Rest well, we will start tomorrow.", zh:"好好休息，我们明天开始。"},
      {role:"S", en:"Hope you had a smooth flight.", zh:"希望您一路飞行顺利。"},
      {role:"W", en:"Yes, on time. Your itinerary is here.", zh:"是的，准点到达。这是您的行程单。"},
      {role:"S", en:"Could we go over the schedule tonight?", zh:"我们今晚过一遍日程可以吗？"},
      {role:"W", en:"Sure, it is on your desk. Please refresh first.", zh:"当然，在您桌上。请先休息调整一下。"},
      {role:"S", en:"Thank you for the warm welcome.", zh:"谢谢您的热情欢迎。"},
      {role:"W", en:"My pleasure. Let us drive to the hotel.", zh:"我的荣幸。我们开车去酒店吧。"},
    ],
    speak: ["You must be tired from the flight.", "The car is outside.", "Hope you had a smooth flight."],
    words: [
      {w:"pick up", ph:"/pɪk ʌp/", zh:"接机"},
      {w:"itinerary", ph:"/aɪˈtɪnəreri/", zh:"行程"},
      {w:"hotel", ph:"/hoʊˈtel/", zh:"酒店"},
      {w:"rest", ph:"/rest/", zh:"休息"},
      {w:"schedule", ph:"/ˈskedʒuːl/", zh:"日程"},
      {w:"comfortable", ph:"/ˈkʌmftərbəl/", zh:"舒适"},
      {w:"arrange", ph:"/əˈreɪndʒ/", zh:"安排"},
      {w:"hospitality", ph:"/ˌhɑːspɪˈtæləti/", zh:"款待"},
      {w:"driver", ph:"/ˈdraɪvər/", zh:"司机"},
      {w:"refresh", ph:"/rɪˈfreʃ/", zh:"休息调整"},
      {w:"flight", ph:"/flaɪt/", zh:"航班"},
      {w:"smooth", ph:"/smuːð/", zh:"顺利的"},
      {w:"welcome", ph:"/ˈwelkəm/", zh:"欢迎"},
      {w:"gift", ph:"/ɡɪft/", zh:"礼物"},
    ]
  },
  18: {
    lines: [
      {role:"C", en:"The delivery is late again.", zh:"货又送晚了。"},
      {role:"W", en:"We sincerely apologize for the inconvenience.", zh:"我们诚挚地为带来的不便道歉。"},
      {role:"W", en:"We will resolve it today and compensate you with a discount.", zh:"我们今天会解决，并以折扣补偿您。"},
      {role:"C", en:"This is the third time this month.", zh:"这已经是这个月第三次了。"},
      {role:"W", en:"I understand your frustration. Let me investigate.", zh:"我理解您的懊恼。让我调查一下。"},
      {role:"C", en:"What is your root cause?", zh:"根本原因是什么？"},
      {role:"W", en:"A logistics issue at the port. We will fix it.", zh:"港口的物流问题。我们会修好。"},
      {role:"C", en:"Could I get a refund or replacement?", zh:"我能退款或换货吗？"},
      {role:"W", en:"Both options are available. Which do you prefer?", zh:"两种都可以。您偏好哪一种？"},
      {role:"C", en:"Replacement, please. And improve your process.", zh:"请换货。并改进你们的流程。"},
    ],
    speak: ["We sincerely apologize for the inconvenience.", "We will resolve it today.", "We will compensate you with a discount."],
    words: [
      {w:"complaint", ph:"/kəmˈpleɪnt/", zh:"投诉"},
      {w:"apologize", ph:"/əˈpɑːlədʒaɪz/", zh:"道歉"},
      {w:"inconvenience", ph:"/ˌɪnkənˈviːniəns/", zh:"不便"},
      {w:"resolve", ph:"/rɪˈzɑːlv/", zh:"解决"},
      {w:"compensate", ph:"/ˈkɑːmpenseɪt/", zh:"补偿"},
      {w:"sincere", ph:"/sɪnˈsɪr/", zh:"诚挚"},
      {w:"improve", ph:"/ɪmˈpruːv/", zh:"改进"},
      {w:"investigate", ph:"/ɪnˈvestɪɡeɪt/", zh:"调查"},
      {w:"refund", ph:"/ˈriːfʌnd/", zh:"退款"},
      {w:"replacement", ph:"/rɪˈpleɪsmənt/", zh:"换货"},
      {w:"logistics", ph:"/loʊˈdʒɪstɪks/", zh:"物流"},
      {w:"frustration", ph:"/frʌˈstreɪʃn/", zh:"沮丧"},
      {w:"root cause", ph:"/ruːt kɔːz/", zh:"根本原因"},
      {w:"process", ph:"/ˈprɑːses/", zh:"流程"},
    ]
  },
  19: {
    lines: [
      {role:"S", en:"Friends, I believe in our vision.", zh:"朋友们，我坚信我们的愿景。"},
      {role:"S", en:"The market gives us a rare opportunity.", zh:"市场给了我们难得的机会。"},
      {role:"S", en:"If we work together, we will achieve what others think impossible.", zh:"如果我们齐心协力，就能达成别人认为不可能的事。"},
      {role:"S", en:"The future is promising. Let us build it now.", zh:"未来充满希望。让我们现在就着手打造。"},
      {role:"S", en:"Every milestone we have reached is proof of our drive.", zh:"我们达成的每个里程碑，都是我们干劲的证明。"},
      {role:"S", en:"I have seen your commitment in every project.", zh:"我在每个项目里都看到了你们的投入。"},
      {role:"S", en:"Today, we celebrate not just success, but the journey.", zh:"今天，我们庆祝的不只是成功，还有这段历程。"},
      {role:"S", en:"Your passion is what makes our team spirit strong.", zh:"你们的热情让我们的团队精神坚强。"},
      {role:"S", en:"Together, we will write the next chapter.", zh:"携手同行，我们将书写下一章。"},
      {role:"S", en:"Let us begin. Thank you from the bottom of my heart.", zh:"让我们开始吧。发自内心地感谢大家。"},
    ],
    speak: ["I believe in our vision.", "The future is promising.", "Let us build it now."],
    words: [
      {w:"vision", ph:"/ˈvɪʒn/", zh:"愿景"},
      {w:"opportunity", ph:"/ˌɑːpərˈtuːnəti/", zh:"机遇"},
      {w:"together", ph:"/təˈɡeðər/", zh:"携手"},
      {w:"inspire", ph:"/ɪnˈspaɪər/", zh:"激励"},
      {w:"future", ph:"/ˈfjuːtʃər/", zh:"未来"},
      {w:"believe", ph:"/bɪˈliːv/", zh:"相信"},
      {w:"achieve", ph:"/əˈtʃiːv/", zh:"达成"},
      {w:"passion", ph:"/ˈpæʃn/", zh:"热情"},
      {w:"commitment", ph:"/kəˈmɪtmənt/", zh:"承诺"},
      {w:"drive", ph:"/draɪv/", zh:"动力"},
      {w:"milestone", ph:"/ˈmaɪlstoʊn/", zh:"里程碑"},
      {w:"team spirit", ph:"/tiːm ˈspɪrɪt/", zh:"团队精神"},
      {w:"celebrate", ph:"/ˈselɪbreɪt/", zh:"庆祝"},
      {w:"journey", ph:"/ˈdʒɜːrni/", zh:"旅程"},
    ]
  },
  20: {
    lines: [
      {role:"A", en:"Mr. Smith, welcome to China! Let us toast to cooperation.", zh:"Smith 先生，欢迎来到中国！为合作干杯。"},
      {role:"B", en:"Cheers! I look forward to the meeting.", zh:"干杯！我期待这次会议。"},
      {role:"A", en:"Today I will present three points about our plan.", zh:"今天我将演示我们计划的三点。"},
      {role:"B", en:"Good. If the price works, we have a deal.", zh:"好。如果价格谈得拢，我们就成交。"},
      {role:"A", en:"I believe in our shared vision.", zh:"我相信我们共同的愿景。"},
      {role:"B", en:"The future looks promising indeed.", zh:"未来确实充满希望。"},
      {role:"A", en:"Could you put yourself on mute for the presentation?", zh:"演示时请您静音好吗？"},
      {role:"B", en:"Done. Let me highlight the key point.", zh:"好了。我来强调关键点。"},
      {role:"A", en:"Any other questions before we sign?", zh:"签约前还有其他问题吗？"},
      {role:"B", en:"None. We have a win-win deal. Let us build it now.", zh:"没有了。我们达成了双赢交易。让我们现在就着手打造。"},
    ],
    speak: ["Let us toast to cooperation.", "Today I will present three points.", "If the price works, we have a deal."],
    words: [
      {w:"welcome", ph:"/ˈwelkəm/", zh:"欢迎"},
      {w:"toast", ph:"/toʊst/", zh:"祝酒"},
      {w:"present", ph:"/prɪˈzent/", zh:"演示"},
      {w:"negotiate", ph:"/nɪˈɡoʊʃieɪt/", zh:"谈判"},
      {w:"believe", ph:"/bɪˈliːv/", zh:"相信"},
      {w:"achieve", ph:"/əˈtʃiːv/", zh:"达成"},
      {w:"vision", ph:"/ˈvɪʒn/", zh:"愿景"},
      {w:"deal", ph:"/diːl/", zh:"交易"},
      {w:"win-win", ph:"/wɪn wɪn/", zh:"双赢"},
      {w:"future", ph:"/ˈfjuːtʃər/", zh:"未来"},
      {w:"highlight", ph:"/ˈhaɪlaɪt/", zh:"强调"},
      {w:"key point", ph:"/kiː pɔɪnt/", zh:"要点"},
      {w:"cooperation", ph:"/koʊˌɑːpəˈreɪʃn/", zh:"合作"},
      {w:"shared", ph:"/ʃerd/", zh:"共同的"},
    ]
  },
};
